# Generated by Django 5.2.14 on 2026-05-18 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название актива')),
                ('ticker', models.CharField(blank=True, max_length=20, verbose_name='Тикер')),
                ('asset_type', models.CharField(choices=[('stock', 'Акция'), ('bond', 'Облигация'), ('etf', 'ETF'), ('cash', 'Деньги'), ('crypto', 'Криптовалюта'), ('metal', 'Драгметалл'), ('other', 'Другое')], max_length=20, verbose_name='Тип актива')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость позиции')),
                ('expected_return', models.FloatField(verbose_name='Ожидаемая доходность, %')),
                ('risk', models.FloatField(verbose_name='Риск, %')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Актив',
                'verbose_name_plural': 'Активы',
            },
        ),
    ]
