# Generated by Django 5.2.14 on 2026-05-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Текущая цена'),
        ),
        migrations.AddField(
            model_name='asset',
            name='quantity',
            field=models.FloatField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость позиции'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('stock', 'Акция'), ('bond', 'Облигация'), ('etf', 'ETF'), ('cash', 'Деньги'), ('crypto', 'Криптовалюта'), ('metal', 'Драгметалл'), ('other', 'Другое')], default='stock', max_length=20, verbose_name='Тип актива'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='expected_return',
            field=models.FloatField(default=10, verbose_name='Ожидаемая доходность, %'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='risk',
            field=models.FloatField(default=15, verbose_name='Риск, %'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='ticker',
            field=models.CharField(max_length=30, verbose_name='Тикер'),
        ),
    ]
