# Generated by Django 5.2.15 on 2026-06-09 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_asset_current_price_asset_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='avg_buy_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Средняя цена покупки'),
        ),
        migrations.AddField(
            model_name='asset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='Валюта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Портфель',
                'verbose_name_plural': 'Портфели',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.portfolio', verbose_name='Портфель'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('buy', 'Покупка'), ('sell', 'Продажа'), ('dividend', 'Дивиденд'), ('deposit', 'Пополнение'), ('withdraw', 'Вывод')], max_length=20, verbose_name='Тип операции')),
                ('quantity', models.FloatField(default=0, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Комиссия')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.asset', verbose_name='Актив')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('open', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Открытие')),
                ('high', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Максимум')),
                ('low', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Минимум')),
                ('close', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Закрытие')),
                ('volume', models.BigIntegerField(default=0, verbose_name='Объём')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='core.asset', verbose_name='Актив')),
            ],
            options={
                'verbose_name': 'История цен',
                'verbose_name_plural': 'История цен',
                'ordering': ['-date'],
                'unique_together': {('asset', 'date')},
            },
        ),
    ]
