# Generated by Django 5.2.15 on 2026-06-09 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_asset_avg_buy_price_asset_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='asset_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Название актива'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='asset_ticker',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Тикер актива'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='avg_buy_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Средняя цена покупки'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.asset', verbose_name='Актив'),
        ),
    ]
