# Generated by Django 5.2.15 on 2026-06-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transaction_asset_name_transaction_asset_ticker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='asset_id_snapshot',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID актива'),
        ),
    ]
