# Generated by Django 5.2.15 on 2026-06-09 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transaction_asset_id_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='asset_id_snapshot',
        ),
    ]
